name: dependon
description:
  Simple, light-weight and extremely legible package for dependency injection management.
version: 1.2.0
homepage: https://github.com/ifanger/dependon

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: